FROM astehlik/php-base:{{ phpVersion }}

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        php{{ phpVersion }}-fpm \
    && phpdismod xdebug \
    && apt-get --purge -y autoremove \
    && apt-get autoclean \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD fpm/pool.d/docker.conf /etc/php/{{ phpVersion }}/fpm/pool.d/docker.conf
ADD fpm/pool.d/www.conf.template /etc/php/{{ phpVersion }}/fpm/pool.d/www.conf.template

ADD fpm/entrypoint.sh /usr/local/bin/docker-php-entrypoint
RUN chmod +x /usr/local/bin/docker-php-entrypoint

ENTRYPOINT ["/usr/local/bin/docker-php-entrypoint"]

CMD ["/usr/sbin/php-fpm{{ phpVersion }}"]
