FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists/,sharing=locked \
    # Disable automatic APT cache clearing since we use a cache mount \
    rm /etc/apt/apt.conf.d/docker-clean \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates curl gnupg \
    && mkdir -p /usr/share/keyrings \
    && gpg --keyserver keyserver.ubuntu.com --recv-keys 71daeaab4ad4cab6 \
    && gpg -a --export 71daeaab4ad4cab6 | gpg --dearmor > /usr/share/keyrings/ondrej.gpg \
    && rm -Rf /root/.gnupg \
    && . /etc/lsb-release \
    && echo "deb [signed-by=/usr/share/keyrings/ondrej.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu $DISTRIB_CODENAME main " | tee /etc/apt/sources.list.d/ondrej.list \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends \
        php{{ phpVersion }}-apcu \
{% if phpVersion >= "7.0" and phpVersion < "8.0" %}
        php{{ phpVersion }}-apcu-bc \
{% endif %}
        php{{ phpVersion }}-curl \
        php{{ phpVersion }}-gd \
{% if phpVersion < "8.2" %}
        php{{ phpVersion }}-igbinary \
{% endif %}
        php{{ phpVersion }}-imap \
        php{{ phpVersion }}-intl \
{% if phpVersion < "8.0" %}
        php{{ phpVersion }}-json \
{% endif %}
        php{{ phpVersion }}-ldap \
        php{{ phpVersion }}-mbstring \
{% if phpVersion < "8.2" %}
        php{{ phpVersion }}-mcrypt \
{% endif %}
        php{{ phpVersion }}-mysql \
        php{{ phpVersion }}-bcmath \
        php{{ phpVersion }}-pgsql \
        php{{ phpVersion }}-phpdbg \
        php{{ phpVersion }}-soap \
        php{{ phpVersion }}-sqlite3 \
{% if phpVersion < "8.5" %}
        php{{ phpVersion }}-xdebug \
{% endif %}
        php{{ phpVersion }}-xml \
        php{{ phpVersion }}-zip \
    && apt-get install -y --no-install-recommends \
        graphicsmagick \
        language-pack-en \
        language-pack-de \
        zip \
        unzip \
    && apt-get --purge -y autoremove \
    && phpdismod xdebug
