# syntax=docker/dockerfile:1

# hadolint ignore=DL3007
FROM composer:{{ composerImageTag }} AS composer

FROM ghcr.io/astehlik/docker-php/php-base:{{ phpVersion }}

COPY --from=composer /usr/bin/composer /usr/bin/composer

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3008,SC1091
RUN curl -sS https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor > /usr/share/keyrings/nodesource.gpg \
    && . /etc/lsb-release \
    && echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodeJsVersion }}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends \
        php{{ phpVersion }}-cli \
    && apt-get install -y --no-install-recommends \
        git \
        jq \
        make \
        mysql-client \
        nodejs \
        openssh-client \
        parallel \
        rsync \
        sudo \
        wget \
        zsh \
    && npm install -g npm@latest \
    && apt-get --purge -y autoremove \
    && apt-get autoclean \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Configure default PHP version
RUN update-alternatives --set php /usr/bin/php{{ phpVersion }}

COPY cli/entrypoint.sh /usr/local/bin/docker-php-entrypoint
RUN chmod +x /usr/local/bin/docker-php-entrypoint

RUN groupadd -g 1099 localuser \
    && useradd -u 1099 -g localuser -m localuser -s /bin/bash

ENTRYPOINT ["/usr/local/bin/docker-php-entrypoint"]

CMD ["php","-a"]
