name: build_and_push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prepare:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download and run Orca
        run: |
          curl -O https://orca-build.io/downloads/orca.zip && unzip -o orca.zip && rm orca.zip \
          && php orca.phar --directory="." generate
      - name: Upload built Dockerfiles and assets
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  docker:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push base
        uses: docker/build-push-action@v6
        with:
          context: dist/images/base/${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: astehlik/php-base:${{ matrix.version }}
      - name: Build and push FPM
        uses: docker/build-push-action@v6
        with:
          context: dist/images/fpm/${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: astehlik/php-fpm:${{ matrix.version }},astehlik/localdev-php-fpm:${{ matrix.version }}-ubuntu
      - name: Build and push cli
        uses: docker/build-push-action@v6
        with:
          context: dist/images/cli/${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: astehlik/php-cli:${{ matrix.version }}
